#This workflow deploys to Docker Hub
name: docker-hub-deploy

on:
  push:
    branches: [ "test-deploy" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to DockerHub
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      - name: Logging the github run id
        run: echo Github Run ID - ${{ github.run_id }}
      - name: Authorize DockerHub
        run: echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - name: Docker build tag
        run: docker build -t gscbinc/dashboard-core-dataset-application:0.0.${{ github.run_id }} .
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
