# This workflow deploys and end-to-end test for simulating runs on both new environments and existing environments
name: e2e-testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  e2e-new-env:
    runs-on: ubuntu-latest
    name: End-To-End testing for New Environments
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          name: Project-REFOCUS/mysql-changeset-schematics
          ref: refs/heads/main
        name: Checkout repository mysql-changeset-schematics repo
      - name: Inspect contents of the workspace
        run: ls -a
